I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 854, in script
    if hcover:
  File "game/script.rpy", line 854, in <module>
    if hcover:
NameError: name 'hcover' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 854, in script
    if hcover:
  File "C:\Users\ibrah\OneDrive\Documents\A game renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\ibrah\OneDrive\Documents\A game renpy\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\ibrah\OneDrive\Documents\A game renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 854, in <module>
    if hcover:
NameError: name 'hcover' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
FinLit 1.0
Sun Oct 22 17:54:59 2023
